name: Deploy to GCP VM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "
            cd ${{ secrets.PROJECT_PATH }} &&
            git pull &&
            echo "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}" > ${{ secrets.PROJECT_PATH }}/.env  &&
            echo "APPROVE_ID=${APPROVE_ID}" >> ${{ secrets.PROJECT_PATH }}/.env  &&
            sudo docker compose up -d 
          "
