name: Deploy to GCP VM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "
            echo "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}" > ${{ secrets.PROJECT_PATH }}/.env
            sudo cat <<EOF > telebot.service
              [Unit]
              Description=telebot backend
              After=network.target
          
              [Service]
              Type=simple
              User=${{ secrets.GCP_VM_USER }}
              ExecStart=${{ secrets.PROJECT_PATH }}/venv/bin/python ${{ secrets.PROJECT_PATH }}/app.py
              Restart=on-failure
          
              [Install]
              WantedBy=multi-user.target
              EOF
            sudo mv telebot.service /etc/systemd/system/telebot.service
            cd ${{ secrets.PROJECT_PATH }} &&
            git pull &&
            ${{ secrets.PROJECT_PATH }}/venv/bin/pip install -r requirements.txt &&
            sudo systemctl daemon-reload
            sudo systemctl enable telebot.service
            sudo systemctl restart telebot.service
          "
